let options = [
	{ value: "xamarinIOS", label: "Xamarin.IOS" },
	{ value: "xamarinAndroid", label: "Xamarin.Android" },
	{ value: "xamarinFormsMVVMFramework", label: "Xamarin.Forms MVVM Framework" },
	{ value: "windowsForms", label: "Windows Forms" },
	{ value: "xamarinMvvmCross", label: "Xamarin MvvmCross" },
	{ value: "windowsPhone", label: "Windows Phone 7" },
	{ value: "javeME", label: "Java ME" },
	{ value: "pnoneGap", label: "PnoneGap/Cordova + IONIC Framework" },
	{ value: "c#", label: "C#" },
	{ value: "php", label: "PHP" },
	{ value: "objectuveC", label: "Objectuve-C" },
	{ value: "java", label: "Java" },
	{ value: "aspNet", label: "ASP.NET" },
	{ value: "aspNetCore", label: "ASP.NET Core" },
	{ value: "razor", label: "MVC Razor" },
	{ value: "wcf", label: "WCF" },
	{ value: "entity", label: "Entity Framework" },
	{ value: "nHibernate", label: "NHibernate" },
	{ value: "ado", label: ".ADO" },
	{ value: "mSUnit", label: "MSUnit" },
	{ value: "nunit", label: "Nunit" },
	{ value: "express", label: "Express. js" },
	{ value: "hapi", label: "Hapi" },
	{ value: "coa", label: "COA" },
	{ value: "sails", label: "SailsJS" },
	{ value: "meteor", label: "Meteor JS" },
	{ value: "passport", label: "Passport" },
	{ value: "jwt", label: "JWT" },
	{ value: "mongoose", label: "Mongoose" },
	{ value: "sequelize", label: "Sequelize" },
	{ value: "net", label: ".Net" },
	{ value: "node", label: "Node.js" },
	{ value: "c#Mono", label: "C# Mono" },
	{ value: "soap", label: "Soap API" },
	{ value: "JSONP", label: "JSONP" },
	{ value: "RESTAPI", label: "REST API" },
	{ value: "htmlHtml5", label: "HTML/HTML5" },
	{ value: "javaScript", label: "JavaScript" },
	{ value: "cssCss3", label: "CSS/CSS3" },
	{ value: "typeScript", label: "TypeScript" },
	{ value: "coffeeScript", label: "CoffeeScript" },
	{ value: "jade", label: "Jade" },
	{ value: "sassScss", label: "SASS/SCSS" },
	{ value: "haml", label: "HAML" },
	{ value: "less", label: "LESS" },
	{ value: "es5", label: "ES5" },
	{ value: "es6", label: "ES6" },
	{ value: "es7", label: "ES7" },
	{ value: "es8", label: "ES8" },
	{ value: "bootstrap3", label: "Bootstrap3" },
	{ value: "semanticUI", label: "Semantic UI" },
	{ value: "materialUI", label: "Material UI" },
	{ value: "jQueryAjax", label: "jQuery Ajax" },
	{ value: "knockout", label: "Knockout" },
	{ value: "backbone", label: "Backbone" },
	{ value: "angularJS", label: "Angular JS" },
	{ value: "angular2+", label: "Angular 2+" },
	{ value: "reactJS", label: "React JS" },
	{ value: "vanilaJS", label: "VanilaJS" },
	{ value: "emberJS", label: "EmberJS" },
	{ value: "blaze", label: "Blaze Template" },
	{ value: "foundation", label: "Foundation" },
	{ value: "reactRouter", label: "React Router" },
	{ value: "UIRouter", label: "UI Router" },
	{ value: "lodashUnderscore", label: "lodash/underscore" },
	{ value: "flux", label: "Flux" },
	{ value: "redux", label: "Redux" },
	{ value: "D3", label: "D3" },
	{ value: "RxJS", label: "RxJS" },
	{ value: "MEAN", label: "MEAN (MongoDB, ExpressJS, AngularJS/Angular, NodeJS. based fullstack js framework) Redis/Redis cache" },
	{ value: "SQLite", label: "SQLite" },
	{ value: "MSSQL", label: "MS SQL" },
	{ value: "MySQL", label: "MySQL" },
	{ value: "MongoDB", label: "Mongo DB" },
	{ value: "Iaas", label: "IaaS - Infrastructure as a Service" },
	{ value: "PlatformAsAService", label: "Platform as a Service" },
	{ value: "SoftwareAsAServise", label: "Software as a Servise" },
	{ value: "agile", label: "Agile" },
	{ value: "Scrum", label: "Scrum" },
	{ value: "ArchitectureDesign", label: "Architecture Design" },
	{ value: "UIUX", label: "UI/UX Design" },
	{ value: "js[DOM]", label: "js [DOM]" },
	{ value: "CrossBrowserLayout", label: "Cross-browser layout" },
	{ value: "gulp", label: "gulp" },
	{ value: "grunt", label: "grunt" },
	{ value: "webpack", label: "webpack browserify" },
	{ value: "ShouldJS", label: "Should.JS" },
	{ value: "Supertest", label: "Supertest" },
	{ value: "Mocha", label: "Mocha" },
	{ value: "Protractor", label: "Protractor" },
	{ value: "Karma", label: "Karma" },
	{ value: "Selenium", label: "Selenium" },
	{ value: "Jasmine", label: "Jasmine" },
	{ value: "Doсker", label: "Doсker" }  
];

export default options;
